#!/bin/bash
# ============================================================
# TMS — Deployment Script for VPS
# Server: 5.42.102.58 (Timeweb Cloud, Ubuntu 24.04)
# Usage: bash deploy.sh
# ============================================================

set -euo pipefail

echo "🚛 TMS Deploy Script"
echo "===================="

# --- 1. Install Docker (if not installed) ---
if ! command -v docker &> /dev/null; then
    echo "📦 Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
    echo "✅ Docker installed"
else
    echo "✅ Docker already installed"
fi

# --- 2. Install Docker Compose plugin (if not installed) ---
if ! docker compose version &> /dev/null; then
    echo "📦 Installing Docker Compose plugin..."
    apt-get update && apt-get install -y docker-compose-plugin
    echo "✅ Docker Compose installed"
else
    echo "✅ Docker Compose already installed"
fi

# --- 3. Create project directory ---
PROJECT_DIR="/opt/tms"
if [ ! -d "$PROJECT_DIR" ]; then
    mkdir -p "$PROJECT_DIR"
    echo "📁 Created $PROJECT_DIR"
fi

# --- 4. Verify files exist ---
if [ -f "$PROJECT_DIR/docker-compose.prod.yml" ]; then
    echo "✅ Project files found"
else
    echo "❌ Project files not found in $PROJECT_DIR"
    echo "   Upload via: node scripts/deploy-ssh.mjs"
    exit 1
fi

cd "$PROJECT_DIR"

# --- 5. Create .env if not exists ---
if [ ! -f .env ]; then
    echo "🔐 Creating .env from template..."
    
    # Generate random secrets
    JWT_SECRET=$(openssl rand -hex 32)
    DB_PASS=$(openssl rand -hex 16)
    SEED_PASS=$(openssl rand -base64 16)
    REDIS_PASS=$(openssl rand -hex 16)
    
    cat > .env << EOF
# --- Generated by deploy.sh on $(date -I) ---

# Database
POSTGRES_DB=tms
POSTGRES_USER=tms
POSTGRES_PASSWORD=${DB_PASS}
DATABASE_URL=postgresql://tms:${DB_PASS}@postgres:5432/tms

# Redis
REDIS_PASSWORD=${REDIS_PASS}
REDIS_URL=redis://:${REDIS_PASS}@redis:6379

# API
API_PORT=4000
HOST=0.0.0.0
LOG_LEVEL=info

# Auth
JWT_SECRET=${JWT_SECRET}

# CORS (change to your domain later)
CORS_ORIGIN=http://5.42.102.58:3000

# Seed (for initial db:seed only)
SEED_PASSWORD=${SEED_PASS}

# Business config
FUEL_PRICE_PER_LITER=60
BASE_OPERATIONAL_COST=100000

# Web
WEB_PORT=3000
NEXT_PUBLIC_API_URL=http://5.42.102.58:4000/api
EOF

    echo "✅ .env created with random secrets"
    echo "   JWT_SECRET: ${JWT_SECRET:0:8}..."
    echo "   DB_PASS:    ${DB_PASS:0:8}..."
    echo "   SEED_PASS:  ${SEED_PASS:0:8}..."
    echo "   REDIS_PASS: ${REDIS_PASS:0:8}..."
else
    echo "✅ .env already exists"
    # Migrate: add REDIS_PASSWORD if missing
    if ! grep -q 'REDIS_PASSWORD' .env; then
        REDIS_PASS=$(openssl rand -hex 16)
        echo "" >> .env
        echo "# Redis auth (added by deploy.sh migration)" >> .env
        echo "REDIS_PASSWORD=${REDIS_PASS}" >> .env
        # Update REDIS_URL to include password
        sed -i "s|REDIS_URL=redis://redis:6379|REDIS_URL=redis://:${REDIS_PASS}@redis:6379|" .env
        echo "  🔐 Added REDIS_PASSWORD to existing .env"
    fi
    # Ensure POSTGRES_DB and POSTGRES_USER exist
    if ! grep -q 'POSTGRES_DB=' .env; then
        echo "POSTGRES_DB=tms" >> .env
    fi
    if ! grep -q 'POSTGRES_USER=' .env; then
        echo "POSTGRES_USER=tms" >> .env
    fi
fi

# --- 6. Build and start ---
echo ""
echo "🏗️  Building Docker images..."

# Remove stale files
rm -f apps/web/postcss.config.js 2>/dev/null

docker compose -f docker-compose.prod.yml build

echo ""
echo "🚀 Starting services..."
docker compose -f docker-compose.prod.yml up -d

# --- 7. Wait for health check ---
echo ""
echo "⏳ Waiting for services to start..."
sleep 10

echo ""
echo "🔍 Service status:"
docker compose -f docker-compose.prod.yml ps

# --- 8. Run DB migrations ---
echo ""
echo "🗄️  Running database migrations..."
docker compose -f docker-compose.prod.yml exec -T api node -e "
  import('drizzle-kit').then(() => console.log('Drizzle available'))
" 2>/dev/null || echo "Note: Run migrations manually if needed"

# --- 9. Test health endpoint ---
echo ""
echo "🏥 Health check:"
curl -s http://localhost:4000/api/health | head -c 200 || echo "⚠️ API not ready yet, wait a few seconds"

echo ""
echo ""
echo "============================================"
echo "🎉 TMS Deployed!"
echo "============================================"
echo ""
echo "  API:  http://5.42.102.58:4000/api/health"
echo "  Web:  http://5.42.102.58:3000"
echo ""
echo "  Logs: docker compose -f docker-compose.prod.yml logs -f"
echo "  Stop: docker compose -f docker-compose.prod.yml down"
echo "============================================"
