#!/bin/bash
# ============================================================
# TMS вЂ” Deployment Script for VPS
# Server: 5.42.102.58 (Timeweb Cloud, Ubuntu 24.04)
# Usage: bash deploy.sh
# ============================================================

set -euo pipefail

echo "рџљ› TMS Deploy Script"
echo "===================="

PUBLIC_HOST="${TMS_PUBLIC_HOST:-5.42.102.58}"
PUBLIC_SCHEME="${TMS_PUBLIC_SCHEME:-http}"
PUBLIC_URL="${PUBLIC_SCHEME}://${PUBLIC_HOST}"
COOKIE_SECURE_VALUE="false"
NGINX_CONF_VALUE="./nginx/default.conf"
if [ "$PUBLIC_SCHEME" = "https" ]; then
    COOKIE_SECURE_VALUE="true"
    NGINX_CONF_VALUE="./nginx/default-ssl.conf"
fi

# --- 1. Install Docker (if not installed) ---
if ! command -v docker &> /dev/null; then
    echo "рџ“¦ Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
    echo "вњ… Docker installed"
else
    echo "вњ… Docker already installed"
fi

# --- 2. Install Docker Compose plugin (if not installed) ---
if ! docker compose version &> /dev/null; then
    echo "рџ“¦ Installing Docker Compose plugin..."
    apt-get update && apt-get install -y docker-compose-plugin
    echo "вњ… Docker Compose installed"
else
    echo "вњ… Docker Compose already installed"
fi

# --- 3. Create project directory ---
PROJECT_DIR="/opt/tms"
if [ ! -d "$PROJECT_DIR" ]; then
    mkdir -p "$PROJECT_DIR"
    echo "рџ“Ѓ Created $PROJECT_DIR"
fi

# --- 4. Verify files exist ---
if [ -f "$PROJECT_DIR/docker-compose.prod.yml" ]; then
    echo "вњ… Project files found"
else
    echo "вќЊ Project files not found in $PROJECT_DIR"
    echo "   Upload via: node scripts/deploy-ssh.mjs"
    exit 1
fi

cd "$PROJECT_DIR"

compose() {
    docker compose -f docker-compose.prod.yml "$@"
}

psql_exec() {
    compose exec -T postgres psql -U "${POSTGRES_USER:-tms}" -d "${POSTGRES_DB:-tms}" "$@"
}

psql_file() {
    local file="$1"
    sed 's/--> statement-breakpoint//g' "$file" | psql_exec -v ON_ERROR_STOP=1
}

# --- 5. Create .env if not exists ---
if [ ! -f .env ]; then
    echo "рџ”ђ Creating .env from template..."
    
    # Generate random secrets
    JWT_SECRET=$(openssl rand -hex 32)
    DB_PASS=$(openssl rand -hex 16)
    SEED_PASS=$(openssl rand -base64 16)
    REDIS_PASS=$(openssl rand -hex 16)
    MINIO_PASS=$(openssl rand -hex 16)
    
    cat > .env << EOF
# --- Generated by deploy.sh on $(date -I) ---

# Database
POSTGRES_DB=tms
POSTGRES_USER=tms
POSTGRES_PASSWORD=${DB_PASS}
DATABASE_URL=postgresql://tms:${DB_PASS}@postgres:5432/tms

# Redis
REDIS_PASSWORD=${REDIS_PASS}
REDIS_URL=redis://:${REDIS_PASS}@redis:6379

# API
API_PORT=4000
HOST=0.0.0.0
LOG_LEVEL=info

# Auth
JWT_SECRET=${JWT_SECRET}

# Public URL
DOMAIN=${PUBLIC_HOST}
CORS_ORIGIN=${PUBLIC_URL}

# Seed (for initial db:seed only)
SEED_PASSWORD=${SEED_PASS}

# Business config
FUEL_PRICE_PER_LITER=60
BASE_OPERATIONAL_COST=100000

# Web
WEB_PORT=3000
NEXT_PUBLIC_API_URL=${PUBLIC_URL}/api

# Nginx
NGINX_CONF=${NGINX_CONF_VALUE}

# MinIO (S3-compatible object storage)
MINIO_IMAGE=minio/minio:RELEASE.2025-04-22T22-12-26Z
MINIO_ROOT_USER=tms_minio
MINIO_ROOT_PASSWORD=${MINIO_PASS}
MINIO_PORT=9000
MINIO_CONSOLE_PORT=9001
S3_BUCKET=tms
S3_REGION=us-east-1
S3_PUBLIC_URL=${PUBLIC_URL}/storage

# Cookie
COOKIE_SECURE=${COOKIE_SECURE_VALUE}
EOF

    echo "вњ… .env created with random secrets"
    echo "   JWT_SECRET: ${JWT_SECRET:0:8}..."
    echo "   DB_PASS:    ${DB_PASS:0:8}..."
    echo "   SEED_PASS:  ${SEED_PASS:0:8}..."
    echo "   REDIS_PASS: ${REDIS_PASS:0:8}..."
else
    echo "вњ… .env already exists"
    # Migrate: add REDIS_PASSWORD if missing
    if ! grep -q 'REDIS_PASSWORD' .env; then
        REDIS_PASS=$(openssl rand -hex 16)
        echo "" >> .env
        echo "# Redis auth (added by deploy.sh migration)" >> .env
        echo "REDIS_PASSWORD=${REDIS_PASS}" >> .env
        # Update REDIS_URL to include password
        sed -i "s|REDIS_URL=redis://redis:6379|REDIS_URL=redis://:${REDIS_PASS}@redis:6379|" .env
        echo "  рџ”ђ Added REDIS_PASSWORD to existing .env"
    fi
    # Ensure POSTGRES_DB and POSTGRES_USER exist
    if ! grep -q 'POSTGRES_DB=' .env; then
        echo "POSTGRES_DB=tms" >> .env
    fi
    if ! grep -q 'POSTGRES_USER=' .env; then
        echo "POSTGRES_USER=tms" >> .env
    fi
    if ! grep -q 'MINIO_IMAGE=' .env; then
        echo "MINIO_IMAGE=minio/minio:RELEASE.2025-04-22T22-12-26Z" >> .env
    fi
    if ! grep -q 'NGINX_CONF=' .env; then
        echo "NGINX_CONF=./nginx/default.conf" >> .env
    fi
    if ! grep -q 'DOMAIN=' .env; then
        echo "DOMAIN=${PUBLIC_HOST}" >> .env
    fi
fi

# --- 6. Build and start ---
echo ""
echo "рџЏ—пёЏ  Building Docker images..."

# Remove stale files
rm -f apps/web/postcss.config.js 2>/dev/null

compose build

echo ""
echo "рџљЂ Starting services..."
compose up -d postgres redis minio

# --- 7. Wait for health check ---
echo ""
echo "вЏі Waiting for services to start..."
sleep 10

echo ""
echo "рџ”Ќ Service status:"
compose ps

# --- 7b. Ensure object storage bucket exists ---
echo ""
echo "Ensuring object storage bucket..."
MINIO_USER_VAL=$(grep '^MINIO_ROOT_USER=' .env | cut -d= -f2-)
MINIO_PASS_VAL=$(grep '^MINIO_ROOT_PASSWORD=' .env | cut -d= -f2-)
S3_BUCKET_VAL=$(grep '^S3_BUCKET=' .env | cut -d= -f2-)
S3_BUCKET_VAL=${S3_BUCKET_VAL:-tms}

compose exec -T minio sh -c \
    "mc alias set local http://127.0.0.1:9000 '$MINIO_USER_VAL' '$MINIO_PASS_VAL' >/dev/null && mc mb -p 'local/$S3_BUCKET_VAL' >/dev/null 2>&1 || true"
compose exec -T minio sh -c \
    "mc anonymous set download 'local/$S3_BUCKET_VAL' >/dev/null 2>&1 || true"
echo "  Bucket ${S3_BUCKET_VAL} ready"

# --- 8. Run DB migrations ---
echo ""
echo "рџ—„пёЏ  Running database migrations..."

# Wait for postgres to be healthy
echo "  вЏі Waiting for PostgreSQL..."
for i in $(seq 1 30); do
    if compose exec -T postgres pg_isready -U "${POSTGRES_USER:-tms}" >/dev/null 2>&1; then
        echo "  вњ… PostgreSQL ready"
        break
    fi
    sleep 2
done

BACKUP_DIR="${BACKUP_DIR:-backups}"
mkdir -p "$BACKUP_DIR"
BACKUP_FILE="$BACKUP_DIR/pre-deploy-$(date +%Y%m%d-%H%M%S).dump"
echo "  Creating pre-migration backup: $BACKUP_FILE"
compose exec -T postgres pg_dump -U "${POSTGRES_USER:-tms}" -d "${POSTGRES_DB:-tms}" -Fc > "$BACKUP_FILE"
echo "  Backup ready: $BACKUP_FILE"

# Apply full schema SQL directly via psql
# drizzle uses '--> statement-breakpoint' as delimiter вЂ” replace with semicolons
if [ -f "apps/api/drizzle/0000_full_schema.sql" ]; then
    echo "  рџ“¦ Applying full schema..."
    # Check if tables already exist (idempotent check)
    TABLES_COUNT=$(psql_exec -t \
        -c "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='public';" 2>/dev/null | tr -d ' ')
    if [ "${TABLES_COUNT:-0}" -lt "5" ]; then
        psql_file apps/api/drizzle/0000_full_schema.sql
        echo "  вњ… Schema applied"
    else
        echo "  в„№пёЏ  Tables already exist (${TABLES_COUNT}), skipping schema"
    fi
fi

psql_exec -v ON_ERROR_STOP=1 \
    -c "CREATE TABLE IF NOT EXISTS tms_schema_migrations (tag TEXT PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW());" >/dev/null

for migration in apps/api/drizzle/[0-9][0-9][0-9][0-9]_*.sql; do
    [ -f "$migration" ] || continue
    tag="$(basename "$migration" .sql)"
    if [ "$tag" = "0000_full_schema" ]; then
        continue
    fi

    APPLIED=$(psql_exec -t -A \
        -c "SELECT 1 FROM tms_schema_migrations WHERE tag='${tag}' LIMIT 1;" 2>/dev/null | tr -d '[:space:]')

    if [ "$APPLIED" = "1" ]; then
        echo "  Migration ${tag} already applied"
        continue
    fi

    echo "  Applying migration ${tag}..."
    psql_file "$migration"
    psql_exec -v ON_ERROR_STOP=1 \
        -c "INSERT INTO tms_schema_migrations(tag) VALUES ('${tag}') ON CONFLICT (tag) DO NOTHING;" >/dev/null
done

# --- 8b. Run DB seed (only on fresh DB) ---
echo ""
echo "рџЊ± Running seed..."
# Check if users table is empty (fresh DB)
USER_COUNT=$(psql_exec -t \
    -c "SELECT COUNT(*) FROM users;" 2>/dev/null | tr -d ' ')
if [ "${USER_COUNT:-0}" -eq "0" ]; then
    echo "  рџ“Ґ Seeding fresh database..."
    SEED_PASS_VAL=$(grep '^SEED_PASSWORD=' .env | cut -d= -f2)
    JWT_VAL=$(grep '^JWT_SECRET=' .env | cut -d= -f2)
    compose run --rm \
        -e SEED_PASSWORD="$SEED_PASS_VAL" \
        -e JWT_SECRET="$JWT_VAL" \
        api node apps/api/dist/db/seed.js 2>&1 \
    && echo "  вњ… Seed complete" \
    || echo "  вљ пёЏ  Seed failed вЂ” check logs: docker compose logs api"
else
    echo "  в„№пёЏ  Database has ${USER_COUNT} users, skipping seed"
fi

echo ""
echo "Starting application services..."
compose up -d api web nginx
sleep 10

echo ""
echo "Service status:"
compose ps

# --- 9. Test health endpoint ---
echo ""
echo "рџЏҐ Health check:"
compose exec -T api node -e "fetch('http://127.0.0.1:4000/api/health').then(async r=>{if(!r.ok)process.exit(1); const t=await r.text(); console.log(t.slice(0,200));}).catch(()=>process.exit(1))"
compose exec -T api node -e "fetch('http://127.0.0.1:4000/api/health/ready').then(async r=>{if(!r.ok)process.exit(1); const t=await r.text(); console.log(t.slice(0,200));}).catch(()=>process.exit(1))"

echo ""
echo ""
echo "============================================"
echo "рџЋ‰ TMS Deployed!"
echo "============================================"
echo ""
echo "  API:  ${PUBLIC_URL}/api/health"
echo "  Web:  ${PUBLIC_URL}"
echo ""
echo "  Logs: docker compose -f docker-compose.prod.yml logs -f"
echo "  Stop: docker compose -f docker-compose.prod.yml down"
echo "============================================"
