// ============================================================
// Demo data — pure classification + env-gate helpers.
// Data generator + cleanup pull DB and live in service.ts.
// ============================================================

export const DEMO_PREFIX = '[ДЕМО]';
const DEMO_ORDER_PREFIX = 'DEMO-';
const DEMO_TRIP_PREFIX = 'DEMO-T-';
const DEMO_TRAILER_PREFIX = 'ДМО';

/**
 * Detect whether a row (by its identifying string) was created by
 * the demo generator. Used by `cleanupDemoData` matching and by UI
 * badges that flag demo rows.
 */
export type DemoEntity = 'contractor' | 'vehicle' | 'trailer' | 'driver' | 'order' | 'trip';

export function isDemoFlagged(entity: DemoEntity, value: string | null | undefined): boolean {
    if (!value || typeof value !== 'string') return false;
    switch (entity) {
        case 'contractor':
        case 'vehicle':
        case 'driver':
            return value.startsWith(DEMO_PREFIX);
        case 'trailer':
            return value.startsWith(DEMO_TRAILER_PREFIX);
        case 'order':
            return value.startsWith(DEMO_ORDER_PREFIX);
        case 'trip':
            return value.startsWith(DEMO_TRIP_PREFIX);
    }
}

/**
 * Production safety gate for demo endpoints (A-P2). Mirrors
 * `routes.ts::isDemoSeedAllowed`.
 */
export function isDemoSeedAllowed(env: {
    ALLOW_DEMO_SEED?: string;
    NODE_ENV?: string;
}): boolean {
    if (env.ALLOW_DEMO_SEED === 'true') return true;
    return env.NODE_ENV !== 'production';
}

/**
 * Validate a Russian-style plate generated by the demo seeder. Mirrors
 * the format `${L}${ddd}${LL}77` produced by `rndPlate()` in service.ts.
 */
const DEMO_PLATE_LETTERS = 'АВЕКМНОРСТУХ';

export function isDemoPlateShape(plate: string | null | undefined): boolean {
    if (!plate) return false;
    if (plate.length !== 8) return false;
    const allowed = new Set(DEMO_PLATE_LETTERS.split(''));
    return (
        allowed.has(plate[0]!)
        && /\d{3}/.test(plate.slice(1, 4))
        && allowed.has(plate[4]!)
        && allowed.has(plate[5]!)
        && plate.slice(6) === '77'
    );
}

/**
 * Scenario builder — produces the documented list of demo objects.
 * Pure projection used to assert generator output without inserting
 * rows. (The real generator does this implicitly; we surface it here
 * for tests + docs.)
 */
export interface DemoScenarioSummary {
    contractors: number;
    contracts: number;
    tariffs: number;
    vehicles: number;
    trailers: number;
    drivers: number;
    trips: number;
    orders: number;
}

export const EXPECTED_DEMO_SCENARIO: DemoScenarioSummary = {
    contractors: 1,
    contracts: 1,
    tariffs: 1,
    vehicles: 2,
    trailers: 1,
    drivers: 2,
    trips: 2,
    orders: 3,
};
